services:
  replica0:
    environment:
      - replica_id=0
    build:
      context: .
      dockerfile: replica.dockerfile
    ports:
      - "127.0.0.1:8090:8090"
  replica1:
    environment:
      - replica_id=1
    build:
      context: .
      dockerfile: replica.dockerfile
    ports:
      - "127.0.0.1:8091:8090"
  replica2:
    environment:
      - replica_id=2
    build:
      context: .
      dockerfile: replica.dockerfile
    ports:
      - "127.0.0.1:8092:8090"
  replica3:
    environment:
      - replica_id=3
    build:
      context: .
      dockerfile: replica.dockerfile
    ports:
      - "127.0.0.1:8093:8090"

  proxy0:
    command: sh -c "sleep 20; java -jar /app.jar;"
    environment:
      - proxy_id=0
    build:
      context: .
      dockerfile: proxy.dockerfile
    ports:
      - "127.0.0.1:8080:8080"
  proxy1:
    command: sh -c "sleep 20; java -jar /app.jar;"
    environment:
      - proxy_id=1
    build:
      context: .
      dockerfile: proxy.dockerfile
    ports:
      - "127.0.0.1:8081:8080"
  proxy2:
    command: sh -c "sleep 20; java -jar /app.jar;"
    environment:
      - proxy_id=2
    build:
      context: .
      dockerfile: proxy.dockerfile
    ports:
      - "127.0.0.1:8082:8080"
  proxy3:
    command: sh -c "sleep 20; java -jar /app.jar;"
    environment:
      - proxy_id=3
    build:
      context: .
      dockerfile: proxy.dockerfile
    ports:
      - "127.0.0.1:8083:8080"
