services:
  replica0:
    environment:
      - replica_id=0
    build:
      context: .
      dockerfile: replica.dockerfile
  replica1:
    environment:
      - replica_id=1
    build:
      context: .
      dockerfile: replica.dockerfile
  replica2:
    environment:
      - replica_id=2
    build:
      context: .
      dockerfile: replica.dockerfile
  replica3:
    environment:
      - replica_id=3
    build:
      context: .
      dockerfile: replica.dockerfile

  proxy0:
    command: sh -c "sleep 40; java -jar /app.jar;"
    environment:
      - proxy_id=0
    build:
      context: .
      dockerfile: proxy.dockerfile
    ports:
      - "192.99.168.235:30080:8080"
  proxy1:
    command: sh -c "sleep 40; java -jar /app.jar;"
    environment:
      - proxy_id=1
    build:
      context: .
      dockerfile: proxy.dockerfile
    ports:
      - "192.99.168.235:30081:8080"
  proxy2:
    command: sh -c "sleep 40; java -jar /app.jar;"
    environment:
      - proxy_id=2
    build:
      context: .
      dockerfile: proxy.dockerfile
    ports:
      - "192.99.168.235:30082:8080"
  proxy3:
    command: sh -c "sleep 40; java -jar /app.jar;"
    environment:
      - proxy_id=3
    build:
      context: .
      dockerfile: proxy.dockerfile
    ports:
      - "192.99.168.235:30083:8080"
