services:
  proxy0:
    command: sh -c "java -jar /app.jar;"
    environment:
      - proxy_id=0
    build:
      context: .
      dockerfile: proxy.dockerfile
    ports:
      - "127.0.0.1:8080:8080"
  proxy1:
    command: sh -c "java -jar /app.jar;"
    environment:
      - proxy_id=1
    build:
      context: .
      dockerfile: proxy.dockerfile
    ports:
      - "127.0.0.1:8081:8080"
  proxy2:
    command: sh -c "java -jar /app.jar;"
    environment:
      - proxy_id=2
    build:
      context: .
      dockerfile: proxy.dockerfile
    ports:
      - "127.0.0.1:8082:8080"
  proxy3:
    command: sh -c "java -jar /app.jar;"
    environment:
      - proxy_id=3
    build:
      context: .
      dockerfile: proxy.dockerfile
    ports:
      - "127.0.0.1:8083:8080"
