services:
  proxy0:
    command: sh -c "java -jar /app.jar;"
    environment:
      - proxy_id=0
    build:
      context: .
      dockerfile: proxy.dockerfile
    ports:
      - "192.99.168.235:30080:8080"