services:
  proxy0:
    command: sh -c "java -jar /app.jar;"
    environment:
      - proxy_id=0
    build:
      context: .
      dockerfile: proxy.dockerfile
    ports:
      - "127.0.0.1:8090:8090"